# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
dist: xenial
if: branch = master OR tag IS present OR type = pull_request
julia:
  - 1.3
  - 1.5
notifications:
  email: false
# uncomment the following lines to override the default test script
after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
